## 01. Numpy

- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리에 많이 사용됨

### 1-1. ndarray
- numpy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [3]:
import numpy as np

In [ ]:
# ndarray의 생성
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1.0, 3.14, 1,24])

# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원 수
print(f"배열의 차원: {a.ndim}")

# 데이터 타입
print(f"배열의 데이터 타입: {a.dtype}")
print(f"배열의 데이터 타입: {b.dtype}")

# 형변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터 타입: {new_a.dtype}")

배열의 구조: (2, 3)
배열의 차원: 2
배열의 데이터 타입: int64
배열의 데이터 타입: float64
수정한 배열의 데이터 타입: float64


In [9]:
# 3차원 행렬
a = np.array([[[1,2,3], [4,5,6]],
              [[1,2,3], [4,5,6]],
              [[1,2,3], [4,5,6]]])

print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (3, 2, 3)
배열의 차원: 3


In [ ]:
# 4차원 행렬
a = np.array([[[[1,2,3],[4,5,6]],
              [[1,2,3],[4,5,6]],
              [[1,2,3],[4,5,6]]],
              [[[1,2,3],[4,5,6]],
              [[1,2,3],[4,5,6]],
              [[1,2,3],[4,5,6]]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (2, 3, 2, 3)
배열의 차원: 4


### 1-2. 배열 초기화

In [12]:
# 모든 요소가 0인 배열 생성
np.zeros((3,4)) #2차원
np.zeros((2,3,4),dtype=np.int64) #3차원

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [14]:
# 모든 요소가 1인 배열 생성
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2,3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [18]:
# 주어진 값으로 채운 배열
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
# 단위 행렬
np.eye(3, 3)
np.eye(3,5,1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

### 1-3. 범위 기반 배열 생성

In [24]:
# arange : range()와 유사한 기능 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [ ]:
# linspace : 시작~끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함

np.linspace(10, 100, 10)
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### 1-4. 랜덤 배열 생성

In [29]:
# random.rand(m,n) : 0 ~ 1 사이의 난수로 초기화
np.random.rand(2, 3)

array([[0.34494651, 0.13329106, 0.12887651],
       [0.98888501, 0.73336365, 0.63387088]])

In [33]:
# random.randn(m, n) : 표준정규분포를 따르는 난수로 초기화
# 표준정규분포 : 평균 0, 분산 1인 정규분포
np.random.randn(2, 4, 5)

# random.randint(low, high, (size))
np.random.randint(10, 20, (2,4))

array([[18, 14, 18, 19],
       [17, 12, 10, 12]], dtype=int32)

In [43]:
# random.seed() : 난수 생성시 시작값 제공
np.random.seed(42)
np.random.randn(2,3)

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696]])

In [46]:
# RNG(Random Numbwer Genenrator) : 최근 Numpy 사용에서 권장되는 방식
from numpy.random import default_rng

rng = default_rng(seed=42)
rng2 = default_rng(seed=10)

print(rng.random((3,2)))
print(rng2.random((3,2)))

[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]
[[0.95600171 0.20768181]
 [0.82844489 0.14928212]
 [0.51280462 0.1359196 ]]


In [58]:
# 실습1. 배열 초기화 및 생성(1)
# 1. 0으로 채워진 크기 (3, 4) 배열을 생성한 후, 모든 값을 5로 채우는 새로운 배열을 만드세요. 
a1 = np.zeros((3,4))
a1_2 = np.full((3,4), 5)
print("문제1:", a1, a1_2, a1 + a1_2, sep="\n")

# 2. 0부터 20까지 2씩 증가하는 1차원 배열을 생성하세요.
a2 = np.arange(0,21,2)
print("\n문제2:", a2)

# 3. 0~1 사이의 실수 난수를 가지는 (2, 3) 크기의 배열을 생성하세요.
a3 = np.random.rand(2,3)
# print("\n문제3:", a3)

# 4. 평균이 100, 표준편차가 20인 정규분포 난수 6개를 생성하세요.
# (평균, 표준편차, 개수)
a4 = np.random.normal(100, 20, 6)
# print("\n문제4:", a4)

# 5. 1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4, 5) 크기의 2차원 배열로 변환하세요.
a5 = np.arange(1,21).reshape(4,5)
# print("\n문제5:", a5)

# 6. 0부터 1까지 균등 간격으로 나눈 12개의 값을 가지는 배열을 생성하고, 이를 (3, 4) 크기로 변환하세요. 
a6 = np.linspace(0, 1, 12).reshape(3,4)
# print("\n문제6:", a6)

# 7. 0~99 사이의 정수 난수로 이루어진 (10, 10) 배열을 생성한 뒤,
# np.eye()로 만든 단위 행렬을 더하여 대각선 요소가 1씩 증가된 배열을 만드세요.
a7 = np.random.randint(0, 100, (10, 10))
a7_eye = np.eye(10)
a7_added = a7 + a7_eye
print("\n문제7:", a7_added)

# 8. 0~9 사이의 정수 난수로 이루어진 (2, 3, 4) 3차원 배열을 생성하세요.
a8 = np.random.randint(0, 10, (2, 3, 4))
print("\n문제8:", a8)

문제1:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]

문제2: [ 0  2  4  6  8 10 12 14 16 18 20]

문제7: [[99. 11. 24. 51. 84. 99. 52. 22. 15. 56.]
 [38. 53. 41. 57. 38. 13. 94.  4. 34. 86.]
 [92. 74. 18. 75.  8. 73. 57. 16.  6. 45.]
 [12. 39. 41.  9. 49. 26. 65.  4. 28. 36.]
 [37. 82.  7. 64. 86. 16. 70. 88. 44.  3.]
 [35. 69. 30. 18. 60. 54. 38. 90. 73. 89.]
 [18. 38. 66. 44. 12. 91. 58. 19. 91. 71.]
 [60. 38.  0.  2. 76. 91. 61. 63. 24. 55.]
 [32. 37.  5. 57. 43. 44. 31. 44. 61. 46.]
 [20. 79. 84. 74. 35. 98. 18. 19. 56. 18.]]

문제8: [[[8 0 0 4]
  [5 5 2 6]
  [8 9 7 5]]

 [[7 4 7 9]
  [3 9 7 9]
  [1 4 8 3]]]


### 1-5. 인덱싱과 슬라이싱
- 다차원 배열을 다루는 편의 기능 제공
- Python의 시퀀스보다 빠름

In [59]:
# 인덱싱
a = np.array([10,20,30,40,50])
print(a[2])
print(a[-1])

30
50


In [62]:
# 다차원 인덱싱
# 파이썬 리스트
matrix = [[1,2,4], [4,5,6]]
print("파이썬 인덱싱:", matrix[1][1])

# numpy 배열
a2 = np.array([[1,2,4], [4,5,6]])
print("numpy 인덱싱:", a2[1,1])

# 3차원 배열 인덱싱
a3 = np.arange(24).reshape(2,3,4)
print(a3)
print("3차원 인덱싱:", a3[1,1,1])

파이썬 인덱싱: 5
numpy 인덱싱: 5
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3차원 인덱싱: 17


In [63]:
# 슬라이싱
# arr[행_슬라이스, 열_슬라이스]
# arr[..., 4차원 슬라이스, 3차원 슬라이스, 2차원, 1차원]

a1 = np.array([10,20,30,40,50])
print(a1[1:3])
print(a1[2:])
print(a1[:2])
print(a1[:])
print(a1[::2])
print(a1[::-1])

[20 30]
[30 40 50]
[10 20]
[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]


In [65]:
# 파이썬 리스트와의 차이
# 파이썬 리스트
py_list = [10,20,30,40,50]
sliced = py_list[1:4]
sliced[1] = 100
print("py원본:", py_list)
print("py슬라이싱:", sliced)
print()

# numpy 배열
a1 = np.array([10, 20, 30, 40, 50])
a1_sliced = a1[1:4]
a1_sliced[1] = 100
print("numpy원본:", a1)
print("numpy슬라이싱:", a1_sliced)


py원본: [10, 20, 30, 40, 50]
py슬라이싱: [20, 100, 40]

numpy원본: [ 10  20 100  40  50]
numpy슬라이싱: [ 20 100  40]


In [7]:
# 2차원 배열 슬라이싱

a2 = np.arange(1,21).reshape(4,5)
print(a2)

# 행 슬라이싱
# print(a2[0])
# print(a2[1])
# print(a2[1:3])
# print(a2[2:])
# print()

# 열 슬라이싱
print(a2[:, 2])
print(a2[:, -1])
print(a2[:, 1:3])
print()

# 행과 열 슬라이싱
print(a2[1:3, 2:4])
print(a2[2: , 3: ])
print(a2[::2, ::2])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 3  8 13 18]
[ 5 10 15 20]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]

[[ 8  9]
 [13 14]]
[[14 15]
 [19 20]]
[[ 1  3  5]
 [11 13 15]]


In [9]:
# 3차원 슬라이싱
a3 = np.arange(36).reshape(3, 3, 4)
print(a3)
print(a3[1, 1, 1:3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
[17 18]


In [10]:
# 얕은 복사 : 복사본이 원본과 메모리를 공유 -> 변경사항이 서로에게 영향을 줌

a1 = np.array([1,2,3])
a1_viewd = a1.view()
a1_viewd[1] = 10
print("원본", a1)
print("복사본", a1_viewd)
print()

# 깊은 복사 : 복사본이 원본과 독립적으로 복사됨 -> 서로 영향을 주지 X
a2 = np.array([1,2,3])
a2_copied = a2.copy()
a2_copied[1] = 10
print("원본2", a2)
print("복사본2", a2_copied)

원본 [ 1 10  3]
복사본 [ 1 10  3]

원본2 [1 2 3]
복사본2 [ 1 10  3]


In [14]:
# Fancy Indexing
# 정수 배열을 사용하여 여러 인덱스로 여러 요소를 한번에 선택
af = np.arange(1,21)
print(af)
print(af[[4, 7, 11]])

af2 = np.arange(1,21).reshape(4,5)
print(af2)
print(af2[[1,3] , [2,4]])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 5  8 12]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 8 20]


In [18]:
# Boolean Indexing
ab = np.linspace(10, 100, 10)
print(ab)
print(ab[ab > 40])
print()

# Boolean masking
ab2 = np.arange(0, 21)
print(ab2)
mask = ab2 % 2 == 0
print(mask)
print(ab2[mask])


[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 50.  60.  70.  80.  90. 100.]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [19]:
# 실습2
# 1. 다음 배열에서 2, 4, 6번째 요소를 Fancy Indexing으로 선택하세요.
arr = np.arange(10, 30, 2)
print(arr)
answer = arr[[1,3,5]]
print(answer)

[10 12 14 16 18 20 22 24 26 28]
[12 16 20]


In [21]:
# 2. 3x3 배열에서 왼쪽 위 → 오른쪽 아래 대각선의 요소만 인덱싱으로 추출하세요.
arr = np.arange(1, 10).reshape(3, 3)
print(arr)
arr[[0,1,2],[0,1,2]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [23]:
# 3. 3x4 배열에서 마지막 열만 선택해 모두 -1로 변경하세요.
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
arr[:, -1] = -1
arr

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3, -1],
       [ 5,  6,  7, -1],
       [ 9, 10, 11, -1]])

In [30]:
# 4. 4x4 배열에서 행을 역순, 열을 역순으로 각각 슬라이싱해 출력하세요.
arr = np.arange(1, 17).reshape(4, 4)
print(arr)

print("행 역순:", arr[::-1])

print("열 역순:", arr[:,::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
행 역순: [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
열 역순: [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [33]:
# 5. 4x5 배열에서 가운데 2x3 부분을 슬라이싱한 뒤 copy()를 이용해 독립 배열을 만드세요.
arr = np.arange(1, 21).reshape(4, 5)
print(arr)

arr_copied = arr[1:3, 1:4].copy()
print(arr_copied)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8  9]
 [12 13 14]]


In [35]:
# 6. 3x4 배열에서 짝수이면서 10 이상인 값만 선택하세요.
arr = np.array([[ 4,  9, 12,  7],
                [10, 15, 18,  3],
                [ 2, 14,  6, 20]])
print(arr[(arr % 2 == 0) & (arr >= 10)])

[12 10 18 14 20]


In [38]:
# 7. 5x5 배열에서 2, 4번째 행을 선택하고, 선택된 행에서 열 순서를 [4, 0, 2]로 재배치하세요.
arr = np.arange(1, 26).reshape(5, 5)
print(arr)
result = arr[[1,3]]
print(result)

result[:, [4, 0, 2]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 6  7  8  9 10]
 [16 17 18 19 20]]


array([[10,  6,  8],
       [20, 16, 18]])

In [39]:
# 8. 5x3 배열에서 각 행의 첫 번째 값이 50 이상인 행만 Boolean Indexing으로 선택하세요.
arr = np.array([[10, 20, 30],
                [55, 65, 75],
                [40, 45, 50],
                [70, 80, 90],
                [15, 25, 35]])

arr[arr[: ,0] >= 50 ]

array([[55, 65, 75],
       [70, 80, 90]])

In [40]:
# 9. 4x4 배열에서 (0,1), (1,3), (2,0), (3,2) 위치의 요소를 한 번에 선택하세요.
arr = np.arange(1, 17).reshape(4, 4)
arr[[0,1,2,3],[1,3,0,2]]

array([ 2,  8,  9, 15])

In [43]:
# 10. 3차원 배열 (2, 3, 4)에서 모든 블록에서 두 번째 열만 추출해 새로운 2차원 배열 (2, 3)을 만드세요.
arr3d = np.arange(24).reshape(2, 3, 4)
print(arr3d)

arr3d[:, :, 1]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 1,  5,  9],
       [13, 17, 21]])

In [45]:
# 실습3.
# 문제1. 0부터 24까지 정수를 가진 배열을 만들고,
# (5, 5) 배열로 변환한 뒤 가운데 행(3번째 행)과 가운데 열(3번째 열)을 각각 1차원 배열로 출력하세요.
a1 = np.arange(25).reshape(5,5)
print(a1)

print(a1[2])
print(a1[:,2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[10 11 12 13 14]
[ 2  7 12 17 22]


In [48]:
# 문제2. 0~99 정수난수로 이루어진 (10, 10) 배열을 생성하고,
# 짝수 인덱스의 행만 선택하여 출력하세요.
a2 = np.random.randint(0, 100, (10, 10))
print(a2)
print()
print(a2[::2])

[[36 34 39 80  4 85 41 32 66 61]
 [95 39 11 48 47 83 34 19 91 72]
 [97 61 89 70 28  3 84 74 11 34]
 [67 91 15 17 29 74 73 52 26 80]
 [92 47  5 43 12 67 97 13 74 42]
 [72 48 81 77 27 26 34 42 21 74]
 [92 46 88 70 32  1 96 71 37 68]
 [ 3 81 73 60 71 39 43 37 41 93]
 [95 73 92 21 74 80 16 12 80 74]
 [19 61 33 44  2 43 81 88 15 77]]

[[36 34 39 80  4 85 41 32 66 61]
 [97 61 89 70 28  3 84 74 11 34]
 [92 47  5 43 12 67 97 13 74 42]
 [92 46 88 70 32  1 96 71 37 68]
 [95 73 92 21 74 80 16 12 80 74]]


In [50]:
# 문제3. 0부터 49까지 정수를 가진 배열을 (5, 10) 배열로 변환한 후,
# 2행 3열부터 4행 7열까지의 부분 배열을 추출하세요.
a3 = np.arange(50).reshape(5,10)
print(a3)

print(a3[1:4, 2:7])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]]


In [54]:
# 문제4. 
# 0~9 난수로 이루어진 (4, 4) 배열을 생성하고, 각각 인덱싱으로 추출해 출력하세요.(for 이용)
# 주대각선 요소 (왼쪽 위 → 오른쪽 아래)
# 부대각선 요소 (오른쪽 위 → 왼쪽 아래)
a4 = np.random.randint(0,10,(4,4))
print(a4)
print(a4[[0,1,2,3],[0,1,2,3]])
print(a4[[0,1,2,3],[3,2,1,0]])

print()
answer = []
answer2 = []
for i in range(4):
  answer.append(a4[i][i])
  answer2.append(a4[i][3 - i])
print("주대각선:\n", answer)
print("부대각선:\n", answer2)

[[9 9 9 8]
 [1 6 7 4]
 [2 2 3 0]
 [2 0 0 4]]
[9 6 3 4]
[8 7 2 2]

주대각선:
 [np.int32(9), np.int32(6), np.int32(3), np.int32(4)]
부대각선:
 [np.int32(8), np.int32(7), np.int32(2), np.int32(2)]


In [56]:
# 문제5.
# 0~9 난수로 이루어진 (3, 4, 5) 3차원 배열을 생성하고,
# 두 번째 층에서 첫 번째 행과 마지막 열의 값을 출력하세요.
a5 = np.random.randint(0,10,(3,4,5))
print(a5)

print(a5[1, 0, -1])

[[[5 2 5 1 3]
  [4 2 4 0 2]
  [1 9 7 1 0]
  [8 3 1 3 9]]

 [[4 9 8 5 1]
  [1 4 8 9 5]
  [0 4 6 2 3]
  [0 7 4 4 7]]

 [[3 0 2 5 3]
  [1 2 8 0 1]
  [5 0 4 8 0]
  [9 7 9 4 8]]]
1


In [58]:
# 문제6. 35부터 74까지의 순차적인 정수로 이루어진 1차원 배열을 만들고
# 10x4 행렬로 변환 후 출력해주세요.
a6 = np.arange(35,75).reshape(10,4)
print("문제6\n", a6)

# 문제7. 6번에서 만든 배열을 맨 끝의 행부터 역순으로 출력해주세요.
a7 = a6[::-1]
print("문제7\n", a7)

# 문제8. 6번에서 만든 배열 중 두 번째 행부터 마지막 직전 행까지,
# 세번째 열부터 마지막 열까지 슬라이싱해서 출력해주세요.
a8 = a6[1:-1, 2:]
print("문제8\n", a8)

문제6
 [[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
문제7
 [[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
문제8
 [[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [60]:
# 문제9. 1부터 50까지의 정수 난수로 된 5x6 배열을 만들고, 배열에서 짝수만 선택하여 출력하는 코드를 작성하세요.
arr = np.random.randint(1, 51, (5, 6))
print(arr)
mask = arr % 2 == 0
# print(mask)
a9 = arr[mask]
print(a9)

[[19 35  9 31  9 48]
 [21  8 47  3  6 11]
 [14 17 10 35 23 15]
 [11 36 47 44  9 13]
 [41 13  4  9 47  8]]
[48  8  6 14 10 36 44  4  8]


In [62]:
# 문제10. 0부터 99까지의 정수로 이루어진 (10, 10) 배열을 생성한 후,
# [1, 3, 5]번째 행과 [2, 4, 6]번째 열의 교차하는 원소들만 선택하여 출력하세요.
arr = np.arange(100).reshape(10,10)
print(arr)

# seleted_row = arr[[1,3,5]]

a10 = arr[[1,3,5]][:, [2,4,6]]
print(a10)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[12 14 16]
 [32 34 36]
 [52 54 56]]


In [63]:
# 문제11.
# 0~9 정수 난수로 이루어진 1차원 배열(길이 15)을 생성하고,
# 짝수 인덱스 위치에 있는 값들 중에서 5 이상인 값만 선택해 출력하세요.
arr = np.random.randint(0, 10, 15)
print(arr)
even_idx_values = arr[::2]
print(even_idx_values)
mask = even_idx_values >= 5
print(mask)
a11 = even_idx_values[mask]
print(a11)

[1 8 2 0 4 0 3 6 3 4 5 9 9 6 1]
[1 2 4 3 3 5 9 1]
[False False False False False  True  True False]
[5 9]
