## 03.NumPy
### 3-1. 배열의 형태 변형과 차원 확장/축소

In [1]:
import numpy as np

In [3]:
# array.ravel()
# - 다차원 배열을 1차원 배열로 펼침
# - 결과를 view로 반환 (view 변경 시 원본도 변경)

a = np.array([[1,2,3], [4,5,6]])
print(a)

flat = a.ravel()
print(flat)

flat[2] = 100
print(flat)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[  1   2 100   4   5   6]
[[  1   2 100]
 [  4   5   6]]


In [5]:
# array.flatten()
# - 다차원 배열을 1차원 배열로 펼침
# - 결과를 복사본으로 반환 (복사본 변경 시 원본은 변경되지 않음)
a = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(a)

flat = a.flatten()
print(flat)

flat[4] = 0
print(flat)
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 0 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# np.expand_dims(a, axis)
# 지정한 위치에 차원 추가 (차원 확장)
# 추가되는 차원은 1
a = np.array([[1,2,3], [4,5,6]])
print("원본:", a.shape)

# axis = 0
a0 = np.expand_dims(a, axis=0)
print("a0", a0.shape)
print("a0", a0)

# axis = 1
a1 = np.expand_dims(a, axis=1)
print("a1", a1.shape)
print("a1", a1)

# axis = 2
a2 = np.expand_dims(a, axis=2)
print("a2", a2.shape)
print("a2", a2)



원본: (2, 3)
a0 (1, 2, 3)
a0 [[[1 2 3]
  [4 5 6]]]
a1 (2, 1, 3)
a1 [[[1 2 3]]

 [[4 5 6]]]
a2 (2, 3, 1)
a2 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [9]:
# np.squeeze(a, axis)
# - 배열에서 크기가 1인 차원을 제거해주는 함수 (차원 축소)
a = np.array([[[[1],[2],[3]]], [[[1],[2],[3]]]])
print(a.shape) # (2, 1, 3, 1)

s = np.squeeze(a)
print(s)
print(s.shape)


(2, 1, 3, 1)
[[1 2 3]
 [1 2 3]]
(2, 3)


In [14]:
# axis 지정하는 경우
a2 = np.zeros((1,4,1,2))
print(a2.shape)

s1 = np.squeeze(a2, axis=0)
print(s1.shape) # (4, 1, 2)

s2 = np.squeeze(a2, axis=2)
print(s2.shape) # (1, 4, 2)


# 차원의 크기가 1이 아닌 차원은 제거할 수 X
# s3 = np.squeeze(a2, axis=1) # error


(1, 4, 1, 2)
(4, 1, 2)
(1, 4, 2)


In [16]:
# np.unique()
# - 배열에서 중복된 요소를 제거
a = np.array([1,1,1, 5,5, 2,2,2,2, 4,4,4, 3,3,3])
u1 = np.unique(a) # 고유값의 오름차순 배열 반환
print(u1)

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스:", idx)
print("원본의 고유값 인덱스:", inv)
print("값의 등장 횟수:", cnt)


[1 2 3 4 5]
인덱스: [ 0  5 12  9  3]
원본의 고유값 인덱스: [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
값의 등장 횟수: [3 4 3 3 2]


In [17]:
# 실습1.
# 문제1. 아래의 배열을 사용해서
# ravel과 flatten을 각각 사용해 1차원 배열로 변환하고,
# arr의 첫 번째 원소(arr[0,0])를 999로 바꾼 뒤 ravel 결과와 flatten 결과에 어떤 변화가 있는지 확인하세요
arr = np.array([[10, 20], [30, 40], [50, 60]])

r = arr.ravel()
f = arr.flatten()
print("r:",r)
print("f:",f)

arr[0,0] = 999
print("r:",r)
print("f:",f)

r: [10 20 30 40 50 60]
f: [10 20 30 40 50 60]
r: [999  20  30  40  50  60]
f: [10 20 30 40 50 60]


In [18]:
# 문제2. 크기가 32x32인 이미지 데이터를 가정하고,
# 이 배열에 대해 expand_dims를 사용하여 shape (1, 32, 32)로 바꾸는 코드를 작성하세요.
img = np.random.rand(32, 32)
img2 = np.expand_dims(img, axis=0)
print(img2)
print(img2.shape)

[[[0.59980008 0.15365084 0.84621667 ... 0.02572967 0.033446   0.73049275]
  [0.60574158 0.25533112 0.45838878 ... 0.63639788 0.284568   0.76010506]
  [0.31291699 0.09355044 0.40184167 ... 0.72401381 0.95326601 0.13949252]
  ...
  [0.71760017 0.31337356 0.49793362 ... 0.54204526 0.64964019 0.19844583]
  [0.18118855 0.4810631  0.5621913  ... 0.85506459 0.04757166 0.7809985 ]
  [0.62006043 0.47499164 0.24489125 ... 0.67375127 0.20425021 0.80262866]]]
(1, 32, 32)


In [19]:
# 문제3.아래 배열에서 불필요한 1차원을 모두 제거하여 shape이 (28, 28)이 되도록 만드세요.
img = np.random.randint(0, 255, (1, 28, 28, 1))
result = np.squeeze(img)
print(result)
print(result.shape)

[[217 133 117  17  83 192 214  58 120 118  42 121  12  51 146 155  88 206
  242  44 170 229 236  34 206  88 129  68]
 [146 163  68 184  36 171 138 135 254 127 129  94  92 183 225  10 229 218
   51  18  70  64 140 196 172 226 203 244]
 [135  66 157 130 235 225  57 146 207 108 117 181 150  14 211 134 105  22
  147 234 249 254 208 192 196  51  75  62]
 [147 119  15  78 130  56 254  65 221 151  28  86 118 129  23 149 128  62
  230 243  26 104 151 190 190 214 170  95]
 [ 78 251 174 175  80 128 213 210 229 199 237 225  96  98 202 131 251 109
  147  47  44 238 198 166 194  11 135  28]
 [170  91  46  17  89  67 222 222 150  54 105 248  99 216  79  79  88 123
  205 146  13 130 181 102  19 105 181 154]
 [ 83 115 100 252   1 214  34 136  78  12   5 160   2  99 109 195 130  54
  187 135 222 237  18 102  74 109 162  78]
 [ 44 221  56 138  25 110 198  49 197  67 110  15 110 156 119 117 158   1
  123 219 244 172 138 170  64  43 237 230]
 [231 168 174 105 227 197 244  12  69  63 166  77 187  56  31 20

In [22]:
# 문제4. 아래 2차원 배열을 
# 1) 1차원 배열로 만든 후
# 2) 중복값을 제거한 뒤 shape (1, n)으로 재구성하세요.
arr = np.array([[3, 1, 2, 2],
                [1, 2, 3, 1],
                [2, 2, 1, 4]])
flat = arr.flatten()
print(flat)
uniq = np.unique(flat)
print(uniq)
result = uniq.reshape(1,-1) # -1을 입력할시 자동으로 계산해줌
print(result)

[3 1 2 2 1 2 3 1 2 2 1 4]
[1 2 3 4]
[[1 2 3 4]]


In [24]:
# 문제5. 다음 배열을 shape (10,)로 만든 뒤 고유값 배열을 구하세요.
arr = np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]])  # shape (1, 10, 1)
s = np.squeeze(arr)
print(s)
u = np.unique(s)
print(u)

[1 3 2 1 3 2 3 1 2 3]
[1 2 3]


In [26]:
# 문제6. 다음 배열을 1차원 배열로 만든 후 고유값만 추출해서
# shape (고유값 개수, 1)인 2차원 배열로 변환하세요.
arr = np.array([ [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],
                [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]] ])  # shape (2, 3, 4)

flat = arr.flatten()
uniq = np.unique(flat)
print(uniq)
print(uniq.shape)
reshaped = np.expand_dims(uniq, axis=1)
print(reshaped)
print(reshaped.shape)

[0 1 2 3 4 5 6 7 8]
(9,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(9, 1)


### 3-2. 배열의 결합과 분리

In [30]:
# np.concatenate()
# 배열 시퀀스를 결합
# 기존 구조 안에서 결합
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

result1 = np.concatenate((a, b), axis=0) # 행
print(result1)
print(result1.shape)

# 결합이 불가 -> 결합하는 axis를 제외한 나머지 차원이 같아야 함
# result2 = np.concatenate((a,b), axis=1)

c = np.array([[7], [8], [9]])
result3 = np.concatenate((result1, c), axis = 1) # 열
print(result3)
print(result3.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 7]
 [3 4 8]
 [5 6 9]]
(3, 3)


In [32]:
# np.stack()
# 새로운 차원을 추가하면서 결합
a = np.array([1,2,3])
b = np.array([4,5,6])

# axis = 0
s1 = np.stack((a,b), axis=0)
print(s1)
print(s1.shape)

# axis = 1
s2 = np.stack((a,b), axis=1)
print(s2)
print(s2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
# hstack()
# - 열 방향(가로)로 결합
a = np.array([1,2,3])
b = np.array([4,5,6])

h = np.hstack((a,b))
print(h)

# vstack() - 행 방향(세로)로 결합
v = np.vstack((a, b))
print(v)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [39]:
# np.split()
# 배열을 여러개의 하위 배열로 분할
a = np.arange(9)
s = np.split(a, 3)

print(a)
print(s)
print(s[0])
print(s[1])
print(s[2])

# 같은 크기로만 나눌 수 있음
# s2 = np.split(a, 4)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[0 1 2]
[3 4 5]
[6 7 8]


In [42]:
a = np.arange(16).reshape(4,4)
print(a)

s1 = np.split(a, [1, 3])
print(s1)
for part in s1:
  print(part)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [43]:
# 실습2.
# 문제1. 다음 두 배열을 행 방향으로 이어붙이세요.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a,b)))

[[1 2]
 [3 4]
 [5 6]]


In [44]:
# 문제2. 아래 배열을 3개로 같은 크기로 분할하세요.
a = np.arange(12)
result = np.split(a,3)
for part in result:
  print(part) 

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [45]:
# 문제3. 다음 배열들을 새로운 축에 쌓아 shape이 (3, 2)인 배열을 만드세요.
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

result = np.stack((a,b,c), axis=0)
print(result)
print(result.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


### 3-3. 배열의 정렬

In [48]:
# np.sort(array)
# 정렬된 복사본 반환
# array.sort()
# 원본 배열을 정렬

# 1차원 배열
a = np.array([3,1,4,2])

# 정렬한 배열을 반환
s = np.sort(a)
print(s)
print(a)

# 원본을 정렬
a.sort()
print(a)

# 내림차순 : sort한 후 배열을 뒤집어야 함
print(a[::-1])

[1 2 3 4]
[3 1 4 2]
[1 2 3 4]
[4 3 2 1]


In [49]:
# 2차원 배열 정렬
a = [[6,5,4], [3,1,2]]
s1 = np.sort(a, axis=0)
print(s1)
s2 = np.sort(a, axis=1)
print(s2)

[[3 1 2]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [50]:
# np.argsort()
# - 정렬 인덱스를 반환

a = np.array([3, 5, 1, 2, 4])
idx = np.argsort(a)
print(idx)
print(a[idx])


[2 3 0 4 1]
[1 2 3 4 5]


In [51]:
# 실습3.
# 문제1.아래의 1차원 배열을 오름차순과 내림차순으로 각각 정렬하는 코드를 작성하세요.
arr = np.array([7, 2, 9, 4, 5])
asc = np.sort(arr)
desc = np.sort(arr)[::-1]
print(asc)
print(desc)

[2 4 5 7 9]
[9 7 5 4 2]


In [52]:
# 문제2. 아래의 2차원 배열에서 각 행(row) 별로 오름차순 정렬된 배열을 구하세요.
arr = np.array([[9, 2, 5],
                [3, 8, 1]])
print(np.sort(arr, axis=1))

[[2 5 9]
 [1 3 8]]


In [53]:
# 문제3. 아래의 1차원 배열에서 정렬 결과(오름차순)가 되는 인덱스 배열을 구하고,
# 그 인덱스를 이용해 원본 배열을 직접 재정렬하는 코드를 작성하세요.
arr = np.array([10, 3, 7, 1, 9])
idx = np.argsort(arr)
s = arr[idx]
print(idx)
print(s)

[3 1 2 4 0]
[ 1  3  7  9 10]


In [54]:
# 문제4. 아래 2차원 배열을 열(column) 기준(axis=0)으로 오름차순 정렬된 배열을 구하세요.
arr = np.array([[4, 7, 2],
								[9, 1, 5],
								[6, 8, 3]])

s = np.sort(arr, axis=0)
print(s)

[[4 1 2]
 [6 7 3]
 [9 8 5]]
