## PyTorch Quiz 2 : 연산

In [1]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [2]:
# 여기에 코드를 작성합니다
t1 = torch.tensor([2,4,6])
t1.add_(5)
print(t1)
t1.sub_(3)
print(t1)

tensor([ 7,  9, 11])
tensor([4, 6, 8])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [3]:
# 여기에 코드를 작성합니다
a = torch.rand(3,3)
b = torch.rand(3,3)

print(a+b)
print(a-b)
print(a*b)
print(a/b)


tensor([[1.0281, 1.9014, 1.0309],
        [1.5530, 1.7134, 1.3783],
        [0.9450, 1.2634, 1.4335]])
tensor([[ 0.3829, -0.0833,  0.7321],
        [-0.0722,  0.2065, -0.1170],
        [-0.6866, -0.1357, -0.2323]])
tensor([[0.2276, 0.9021, 0.1317],
        [0.6016, 0.7233, 0.4715],
        [0.1054, 0.3945, 0.5002]])
tensor([[2.1869, 0.9161, 5.9019],
        [0.9111, 1.2741, 0.8435],
        [0.1584, 0.8061, 0.7211]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [4]:
# 여기에 코드를 작성합니다
ta = torch.tensor([[1,2,3], [4,5,6]])
tb = torch.tensor([[7,8],[9,10],[11,12]])
R = torch.matmul(ta, tb)
print(R)


tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [5]:
# 여기에 코드를 작성합니다
added = R+10
print(added)
answer = torch.clamp(added, max=100)
print(answer)


tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [6]:
# 여기에 코드를 작성합니다
M = torch.tensor([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

answer = torch.sum(M, dim=0)
print(answer)

tensor([55, 60, 65, 70, 75])
