## 02. 텐서의 연산

In [1]:
import torch

### 2-1. 산술연산

In [2]:
x = torch.ones(2,2)
print(x)
x = x * 2
print(x)
x = x + 3
print(x)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[5., 5.],
        [5., 5.]])


In [7]:
x = torch.tensor([[1,2], [3,4]])
y = torch.tensor([[4,3], [2,1]])

# 더하기
add = torch.add(x, y)
print(add)
print(x + y)

# 빼기
sub = torch.sub(x, y)
print(sub)
print(x - y)

# 곱하기
mul = torch.mul(x, y)
print(mul)
print(x * y)

# 나누기
div = torch.div(x, y)
print(div)
print(x / y)

tensor([[5, 5],
        [5, 5]])
tensor([[5, 5],
        [5, 5]])
tensor([[-3, -1],
        [ 1,  3]])
tensor([[-3, -1],
        [ 1,  3]])
tensor([[4, 6],
        [6, 4]])
tensor([[4, 6],
        [6, 4]])
tensor([[0.2500, 0.6667],
        [1.5000, 4.0000]])
tensor([[0.2500, 0.6667],
        [1.5000, 4.0000]])


### 2-2. 바꿔치기 연산
- 연산자의 뒤에 _를 추가한 형태로 사용

In [9]:
x = torch.tensor([[5, 6], [7, 8]])
y = torch.tensor([[3,1], [4,2]])

# x = torch.add(x, y)
x.add_(y)
print(x)

x.fill_(0)
print(x)

tensor([[ 8,  7],
        [11, 10]])
tensor([[0, 0],
        [0, 0]])


### 2-3. 각종 연산

In [10]:
x = torch.tensor([[1.1, 2.2, 3.3],[4, 5, 6],[-1, -3.14, -6]])
print(x)

# 수학 연산
print("절댓값", torch.abs(x))
print("올림", torch.ceil(x))
print("반올림", torch.round(x))
print("내림", torch.floor(x))
print("모든 원소의 합", torch.sum(x))
print("모든 원소의 곱", torch.prod(x))
print("클램프", torch.clamp(x, -2, 2))

tensor([[ 1.1000,  2.2000,  3.3000],
        [ 4.0000,  5.0000,  6.0000],
        [-1.0000, -3.1400, -6.0000]])
절댓값 tensor([[1.1000, 2.2000, 3.3000],
        [4.0000, 5.0000, 6.0000],
        [1.0000, 3.1400, 6.0000]])
올림 tensor([[ 2.,  3.,  4.],
        [ 4.,  5.,  6.],
        [-1., -3., -6.]])
반올림 tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -3., -6.]])
내림 tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -4., -6.]])
모든 원소의 합 tensor(11.4600)
모든 원소의 곱 tensor(-18054.7500)
클램프 tensor([[ 1.1000,  2.0000,  2.0000],
        [ 2.0000,  2.0000,  2.0000],
        [-1.0000, -2.0000, -2.0000]])


In [11]:
x = torch.tensor([[1.1, 2.2, 3.3],[4, 5, 6],[-1, -3.14, -6]])
print(x)

# 통계 연산
print("최솟값", torch.min(x))
print("최댓값", torch.max(x))
print("최솟값의 인덱스", torch.argmin(x))
print("최댓값의 인덱스", torch.argmax(x))
print("평균값", torch.mean(x))
print("표준편차", torch.std(x))
print("중복 제거", torch.unique(torch.tensor([1, 2, 3, 1, 2,2,2,3,2,2,2,3,4])))


tensor([[ 1.1000,  2.2000,  3.3000],
        [ 4.0000,  5.0000,  6.0000],
        [-1.0000, -3.1400, -6.0000]])
최솟값 tensor(-6.)
최댓값 tensor(6.)
최솟값의 인덱스 tensor(8)
최댓값의 인덱스 tensor(5)
평균값 tensor(1.2733)
표준편차 tensor(3.9719)
중복 제거 tensor([1, 2, 3, 4])


In [ ]:
# 차원 지정
x = torch.tensor([[1.1, 2.2, 3.3],
                  [4, 5, 6],
                  [-1, -3.14, -6]])

print("열의 합", torch.sum(x, dim=0))
print("행의 합", torch.sum(x, dim=1))
print("열의 최댓값", torch.max(x, dim=0))
print("행의 최솟값", torch.min(x, dim=1))

열의 합 tensor([4.1000, 4.0600, 3.3000])
행의 합 tensor([  6.6000,  15.0000, -10.1400])
열의 최댓값 torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
행의 최솟값 torch.return_types.min(
values=tensor([ 1.1000,  4.0000, -6.0000]),
indices=tensor([0, 0, 2]))


### 2-4. 내적(dot product) / 행렬의 곱셈

In [14]:
x = torch.tensor([[1,2], [3,4]])
y = torch.tensor([[5,6], [7,8]])

print(torch.matmul(x,y))

tensor([[19, 22],
        [43, 50]])
