## 03. 텐서의 조작

In [2]:
import torch

### 3-1. 인덱싱, 슬라이싱
- numpy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [5]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(x[1,1]) # 5
print(x[2,0]) # 7
print(x[0, :]) # 0행 전체
print(x[:, 2]) # 2열 전체
print(x[[0,1,2], [0,1,2]]) # fancy 인덱싱
print(x[x > 5]) # boolean 인덱싱

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [7]:
x = torch.tensor([10, 20, 30, 40, 50])

x[0] = 100
print(x)

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200, 300, 400])
print(x)

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])


### 3-2. 텐서의 크기, 모양 변경

- torch.view()

In [7]:
x = torch.randn(4, 5)
print(x)
y = x.view(20)
print(y)
z = y.view(5, -1) # -1 -> 자동 계산
print(z)

n = z.view(2, 2, 5)
print(n)

tensor([[-1.3478, -0.8117, -1.1783, -0.5400, -0.3041],
        [-0.0648, -0.1424, -0.1656, -0.1777,  1.1590],
        [ 0.9289, -0.1864,  1.3162,  0.7147,  1.8873],
        [ 0.8744, -0.0563,  1.9068,  0.7453,  0.8682]])
tensor([-1.3478, -0.8117, -1.1783, -0.5400, -0.3041, -0.0648, -0.1424, -0.1656,
        -0.1777,  1.1590,  0.9289, -0.1864,  1.3162,  0.7147,  1.8873,  0.8744,
        -0.0563,  1.9068,  0.7453,  0.8682])
tensor([[-1.3478, -0.8117, -1.1783, -0.5400],
        [-0.3041, -0.0648, -0.1424, -0.1656],
        [-0.1777,  1.1590,  0.9289, -0.1864],
        [ 1.3162,  0.7147,  1.8873,  0.8744],
        [-0.0563,  1.9068,  0.7453,  0.8682]])
tensor([[[-1.3478, -0.8117, -1.1783, -0.5400, -0.3041],
         [-0.0648, -0.1424, -0.1656, -0.1777,  1.1590]],

        [[ 0.9289, -0.1864,  1.3162,  0.7147,  1.8873],
         [ 0.8744, -0.0563,  1.9068,  0.7453,  0.8682]]])


### 3-3. 텐서의 숫자값 얻기
- tensor.item() : 스칼라 값 하나만 존재해야 사용 가능

In [9]:
x = torch.rand(2)
print(x)
print(x[0])

print(x[0].item())

tensor([0.2316, 0.2786])
tensor(0.2316)
0.2315601110458374


### 3-4. 차원 축소 및 증가
#### 차원 축소(제거)
- torch.squeeze() : 크기가 1인 차원을 제거함

In [11]:
t = torch.rand(3, 1, 3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.4609, 0.1623, 0.2626]],

        [[0.9204, 0.7489, 0.2846]],

        [[0.1674, 0.0614, 0.0369]]])
torch.Size([3, 1, 3])
tensor([[0.4609, 0.1623, 0.2626],
        [0.9204, 0.7489, 0.2846],
        [0.1674, 0.0614, 0.0369]])
torch.Size([3, 3])


#### 차원 증가(생성)
- torch.unsqueezze() : dim 설정에 따라 차원을 증가시킴
  - dim은 하나의 차원이 추가되는 인덱스

In [13]:
t = torch.rand(3, 3, 3)
print(t.shape)

# 0 가장 상위 차원 -> 3 가장 하위 차원
ts1 = torch.unsqueeze(t, dim=0)
print(ts1.shape)

ts2 = torch.unsqueeze(t, dim=1)
print(ts2.shape)

ts3 = torch.unsqueeze(t, dim=2)
print(ts3.shape)

ts4 = torch.unsqueeze(t, dim=3)
print(ts4.shape)

torch.Size([3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([3, 1, 3, 3])
torch.Size([3, 3, 1, 3])
torch.Size([3, 3, 3, 1])


### 3-5. 텐서간 결합
- torch.stack() : 동일한 형식의 텐서를 새롭게 그룹화 함 -> 새로운 차원 생성됨

In [15]:
x = torch.tensor([1, 4])
y = torch.tensor([2, 5])
z = torch.tensor([3, 6])
result = torch.stack([x, y, z])
print(result)

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
result2 = torch.stack([a,b])
print(result2)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


- torch.cat() : 데이터를 하나의 텐서로 병합 -> 새로운 차원 생성 X

In [16]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[7,8], [9,10]])

result = torch.cat((a,b), dim=1)
print(result)

tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10]])


## 3-6. 텐서 나누기
- torch.chunk() : 텐서를 지정한 개수에 따라 나눔
  - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐
- torch.split() : 지정한 사이즈에 따라 나눔
  - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐

In [17]:
t = torch.rand(3, 7)
print(t)

t1, t2, t3 = torch.chunk(t, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.1090, 0.0049, 0.9850, 0.3496, 0.9674, 0.8125, 0.8032],
        [0.3863, 0.0595, 0.5477, 0.5486, 0.0660, 0.3991, 0.5929],
        [0.3337, 0.8533, 0.2649, 0.6188, 0.4317, 0.3306, 0.2263]])
tensor([[0.1090, 0.0049, 0.9850],
        [0.3863, 0.0595, 0.5477],
        [0.3337, 0.8533, 0.2649]])
tensor([[0.3496, 0.9674, 0.8125],
        [0.5486, 0.0660, 0.3991],
        [0.6188, 0.4317, 0.3306]])
tensor([[0.8032],
        [0.5929],
        [0.2263]])


In [18]:
t = torch.rand(3,7)
print(t)

# 쪼갤 열의 개수 지정
t1, t2, t3 = torch.split(t, [2, 3, 2], dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.3137, 0.8280, 0.1941, 0.1477, 0.4632, 0.5945, 0.2255],
        [0.4898, 0.2418, 0.4421, 0.6934, 0.0275, 0.5074, 0.9041],
        [0.8690, 0.0967, 0.1675, 0.1271, 0.0193, 0.0375, 0.2528]])
tensor([[0.3137, 0.8280],
        [0.4898, 0.2418],
        [0.8690, 0.0967]])
tensor([[0.1941, 0.1477, 0.4632],
        [0.4421, 0.6934, 0.0275],
        [0.1675, 0.1271, 0.0193]])
tensor([[0.5945, 0.2255],
        [0.5074, 0.9041],
        [0.0375, 0.2528]])
